@startuml
abstract Creator
Creator : {abstract} FactoryMethod()
Creator : AnOperation()

note right
        ...
        product = FactoryMethod()
        ...
end note

class ConcreteCreator
ConcreteCreator -|> Creator
ConcreteCreator : FactoryMethod()

note left
        return new ConcreteProduct
end note


interface Product
class ConcreteProduct
ConcreteProduct -|> Product

ConcreteCreator --> ConcreteProduct
@enduml
